/*
 * Inventory Update API
 * API to update inventory quantities. This specification includes a POST interface for updating inventory items.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dk.rdpl.dih.common.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dk.rdpl.dih.common.model.Inventory;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InventoryItems
 */
public class InventoryItemsTest {
    private final InventoryItems model = new InventoryItems();

    /**
     * Model tests for InventoryItems
     */
    @Test
    public void testInventoryItems() {
        // TODO: test InventoryItems
    }

    /**
     * Test the property 'inventory'
     */
    @Test
    public void inventoryTest() {
        // TODO: test inventory
    }

}
