/*
 * Inventory Update API
 * API to update inventory quantities. This specification includes a POST interface for updating inventory items.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dk.rdpl.dih.common.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dk.rdpl.dih.common.model.InventoryQuantity;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Inventory
 */
public class InventoryTest {
    private final Inventory model = new Inventory();

    /**
     * Model tests for Inventory
     */
    @Test
    public void testInventory() {
        // TODO: test Inventory
    }

    /**
     * Test the property 'productID'
     */
    @Test
    public void productIDTest() {
        // TODO: test productID
    }

    /**
     * Test the property 'warehouseID'
     */
    @Test
    public void warehouseIDTest() {
        // TODO: test warehouseID
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

}
