/*
 * Inventory Update API
 * API to update inventory quantities. This specification includes a POST interface for updating inventory items.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dk.rdpl.dih.common.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InventoryQuantity
 */
public class InventoryQuantityTest {
    private final InventoryQuantity model = new InventoryQuantity();

    /**
     * Model tests for InventoryQuantity
     */
    @Test
    public void testInventoryQuantity() {
        // TODO: test InventoryQuantity
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'measure'
     */
    @Test
    public void measureTest() {
        // TODO: test measure
    }

}
