/*
 * Inventory Update API
 * API to update inventory quantities. This specification includes a POST interface for updating inventory items.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import dk.rdpl.dih.common.ApiException;
import dk.rdpl.dih.common.model.InventoryItems;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Update inventory
     *
     * POST interface to update the inventory.  ### Example POST request body &#x60;&#x60;&#x60;json {   \&quot;Inventory\&quot;: [     {       \&quot;ProductID\&quot;: \&quot;P123\&quot;,       \&quot;WarehouseID\&quot;: \&quot;W456\&quot;,       \&quot;Quantity\&quot;: {\&quot;Count\&quot;: 100, \&quot;Measure\&quot;: \&quot;items\&quot;}     },     {       \&quot;ProductID\&quot;: \&quot;P789\&quot;,       \&quot;WarehouseID\&quot;: \&quot;W101\&quot;,       \&quot;Quantity\&quot;: {\&quot;Count\&quot;: 50, \&quot;Measure\&quot;: \&quot;kg\&quot;}     }   ] } &#x60;&#x60;&#x60; 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void inventoryUpdatePostTest() throws ApiException {
        InventoryItems inventoryItems = null;
        api.inventoryUpdatePost(inventoryItems);
        // TODO: test validations
    }

}
