annotationLibrary: "none"
artifactDescription: "DIH Common"
artifactId: "common"
dateLibrary: "java8"
documentationProvider: "none"
groupId: "dk.rdpl.dih"
modelPackage: "dk.rdpl.dih.common.model"
serializationLibrary: "jackson"
parentArtifactId: "common.parent-pom"
parentGroupId: "dk.rdpl.dih"
parentVersion: "1.0.0"
scmConnection: ""
scmDeveloperConnection: ""
scmUrl: ""
