name: "Testing project"
on: push
jobs:
  test_package:
    runs-on: ubuntu-latest
    name: "Build and Test mvn project"
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Install dependencies
        run: mvn clean install
      - name: Run tests
        run: mvn test
