/*
 * Inventory Update API
 * API to update inventory quantities. This specification includes a POST interface for updating inventory items.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dk.rdpl.dih.common.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dk.rdpl.dih.common.model.InventoryQuantity;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dk.rdpl.dih.common.JSON;

/**
 * An inventory object representing an item in the warehouse.  - &#x60;ProductID&#x60;: Identifier for the product. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-09T11:12:23.212507553+01:00[Europe/Copenhagen]", comments = "Generator version: 7.10.0")
public class Inventory {
  public static final String SERIALIZED_NAME_PRODUCT_I_D = "ProductID";
  @SerializedName(SERIALIZED_NAME_PRODUCT_I_D)
  @javax.annotation.Nonnull
  private String productID;

  public static final String SERIALIZED_NAME_WAREHOUSE_I_D = "WarehouseID";
  @SerializedName(SERIALIZED_NAME_WAREHOUSE_I_D)
  @javax.annotation.Nullable
  private String warehouseID;

  public static final String SERIALIZED_NAME_QUANTITY = "Quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  @javax.annotation.Nullable
  private InventoryQuantity quantity;

  public Inventory() {
  }

  public Inventory productID(@javax.annotation.Nonnull String productID) {
    this.productID = productID;
    return this;
  }

  /**
   * Get productID
   * @return productID
   */
  @javax.annotation.Nonnull
  public String getProductID() {
    return productID;
  }

  public void setProductID(@javax.annotation.Nonnull String productID) {
    this.productID = productID;
  }


  public Inventory warehouseID(@javax.annotation.Nullable String warehouseID) {
    this.warehouseID = warehouseID;
    return this;
  }

  /**
   * Get warehouseID
   * @return warehouseID
   */
  @javax.annotation.Nullable
  public String getWarehouseID() {
    return warehouseID;
  }

  public void setWarehouseID(@javax.annotation.Nullable String warehouseID) {
    this.warehouseID = warehouseID;
  }


  public Inventory quantity(@javax.annotation.Nullable InventoryQuantity quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * Get quantity
   * @return quantity
   */
  @javax.annotation.Nullable
  public InventoryQuantity getQuantity() {
    return quantity;
  }

  public void setQuantity(@javax.annotation.Nullable InventoryQuantity quantity) {
    this.quantity = quantity;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Inventory inventory = (Inventory) o;
    return Objects.equals(this.productID, inventory.productID) &&
        Objects.equals(this.warehouseID, inventory.warehouseID) &&
        Objects.equals(this.quantity, inventory.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productID, warehouseID, quantity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Inventory {\n");
    sb.append("    productID: ").append(toIndentedString(productID)).append("\n");
    sb.append("    warehouseID: ").append(toIndentedString(warehouseID)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ProductID");
    openapiFields.add("WarehouseID");
    openapiFields.add("Quantity");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("ProductID");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Inventory
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Inventory.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Inventory is not found in the empty JSON string", Inventory.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Inventory.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Inventory` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Inventory.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("ProductID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ProductID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ProductID").toString()));
      }
      if ((jsonObj.get("WarehouseID") != null && !jsonObj.get("WarehouseID").isJsonNull()) && !jsonObj.get("WarehouseID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `WarehouseID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("WarehouseID").toString()));
      }
      // validate the optional field `Quantity`
      if (jsonObj.get("Quantity") != null && !jsonObj.get("Quantity").isJsonNull()) {
        InventoryQuantity.validateJsonElement(jsonObj.get("Quantity"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Inventory.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Inventory' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Inventory> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Inventory.class));

       return (TypeAdapter<T>) new TypeAdapter<Inventory>() {
           @Override
           public void write(JsonWriter out, Inventory value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Inventory read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Inventory given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Inventory
   * @throws IOException if the JSON string is invalid with respect to Inventory
   */
  public static Inventory fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Inventory.class);
  }

  /**
   * Convert an instance of Inventory to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

