/*
 * Inventory Update API
 * API to update inventory quantities. This specification includes a POST interface for updating inventory items.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dk.rdpl.dih.common.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dk.rdpl.dih.common.JSON;

/**
 * InventoryQuantity
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-09T11:12:23.212507553+01:00[Europe/Copenhagen]", comments = "Generator version: 7.10.0")
public class InventoryQuantity {
  public static final String SERIALIZED_NAME_COUNT = "Count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  @javax.annotation.Nonnull
  private Integer count;

  /**
   * The unit of measure for the quantity, can be \&quot;items\&quot;, \&quot;kg\&quot;, or \&quot;m3\&quot;.
   */
  @JsonAdapter(MeasureEnum.Adapter.class)
  public enum MeasureEnum {
    ITEMS("items"),
    
    KG("kg"),
    
    M3("m3");

    private String value;

    MeasureEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MeasureEnum fromValue(String value) {
      for (MeasureEnum b : MeasureEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<MeasureEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MeasureEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MeasureEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return MeasureEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      MeasureEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_MEASURE = "Measure";
  @SerializedName(SERIALIZED_NAME_MEASURE)
  @javax.annotation.Nonnull
  private MeasureEnum measure;

  public InventoryQuantity() {
  }

  public InventoryQuantity count(@javax.annotation.Nonnull Integer count) {
    this.count = count;
    return this;
  }

  /**
   * The quantity of the product, must be 0 or more.
   * minimum: 0
   * @return count
   */
  @javax.annotation.Nonnull
  public Integer getCount() {
    return count;
  }

  public void setCount(@javax.annotation.Nonnull Integer count) {
    this.count = count;
  }


  public InventoryQuantity measure(@javax.annotation.Nonnull MeasureEnum measure) {
    this.measure = measure;
    return this;
  }

  /**
   * The unit of measure for the quantity, can be \&quot;items\&quot;, \&quot;kg\&quot;, or \&quot;m3\&quot;.
   * @return measure
   */
  @javax.annotation.Nonnull
  public MeasureEnum getMeasure() {
    return measure;
  }

  public void setMeasure(@javax.annotation.Nonnull MeasureEnum measure) {
    this.measure = measure;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InventoryQuantity inventoryQuantity = (InventoryQuantity) o;
    return Objects.equals(this.count, inventoryQuantity.count) &&
        Objects.equals(this.measure, inventoryQuantity.measure);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, measure);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventoryQuantity {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    measure: ").append(toIndentedString(measure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Count");
    openapiFields.add("Measure");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("Count");
    openapiRequiredFields.add("Measure");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to InventoryQuantity
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InventoryQuantity.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InventoryQuantity is not found in the empty JSON string", InventoryQuantity.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!InventoryQuantity.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `InventoryQuantity` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : InventoryQuantity.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("Measure").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Measure` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Measure").toString()));
      }
      // validate the required field `Measure`
      MeasureEnum.validateJsonElement(jsonObj.get("Measure"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InventoryQuantity.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InventoryQuantity' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InventoryQuantity> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InventoryQuantity.class));

       return (TypeAdapter<T>) new TypeAdapter<InventoryQuantity>() {
           @Override
           public void write(JsonWriter out, InventoryQuantity value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InventoryQuantity read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of InventoryQuantity given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InventoryQuantity
   * @throws IOException if the JSON string is invalid with respect to InventoryQuantity
   */
  public static InventoryQuantity fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InventoryQuantity.class);
  }

  /**
   * Convert an instance of InventoryQuantity to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

